### PR TITLE
Support for processing mesh files offline

### PR DESCRIPTION
**Pull request by maltewi**
Added script 'optimize_meshes'. By calling osgconv, it allows to 
 * convert mesh files to .osgb format. Binary file format improves file loading times
  * perform mesh optimization
  * perform mesh simplification

### CODE REVIEW

**Comment by maltewi** [comment]
Possible extension: 
   - Automatically create URDF file, that replaces original mesh files with .osgb ones.
     This would be an alternative to the feature which automatically chooses the .osgb files instead of what's written in the urdf (from #13, @doudou).

**Comment by doudou** [comment]
I really don't like the very generic `optimize_meshes` name. We have an already fairly polluted bin namespace ...

What about making it a subcommand of `rock-roboviz` ?

~~~
rock-roboviz --optimize-meshes [PATH]
~~~

**Comment by maltewi** [comment]
@doudou 
True its a stupid name.. you won't find it, when you need it. Making it a subcommand is a good idea, but I'm not in the mood of rewriting it in ruby. Renamed it to `rock-roboviz-optimize_meshes`. I think it's okay like that. What do you think?

**Comment by doudou** [comment]
> What do you think?

I would very much try to keep the command namespace small ... I can rewrite it if you would be OK with merging it then.

**Comment by maltewi** [comment]
would be great!

**Comment by doudou** [comment]
done

**Comment by maltewi** [comment]
thanks

**Pull request merged**
