### PR TITLE
add SDF support

### PR DESCRIPTION
**Pull request by doudou**
Depends on:
- [x] https://github.com/rock-gui/gui-control_ui/pull/8

In addition to the SDF support _per se_, there's a change in behavior stuck in there. Instead of running the SmoothVisitor, which can take a lot of time on load-time, the plugin only runs the VBOVisitor, which ensures that OSG uses VBO on modern OpenGL (a.k.a. "everywhere" these days). The reason is that:

- the smooth visitor ended up very expensive in our scenes. This led to serious loading times (in the 30s to 1 min) range. The workflow after this commit was to preprocess mesh files into a .osgb file in the build system (in our case, the Rakefile from our bundle), and have the plugin auto-load a `<filename>.osgb` instead of `<filename>` when requested.
- the VBO visitor divided the rendering times by an order of magnitude (and allowed the usage of opengl debuggers, because a 1 min rendering was logged as less than a GB instead of 15-20GB)

Moreover, this significantly expands the functionality of rock-roboviz to allow spawning a control UI (from gui/control_ui).

### CODE REVIEW

**Comment by planthaber** [comment]
rock-roboviz:99: syntax error, unexpected keyword_elsif, expecting keyword_end
elsif use_test_gui

**Comment by doudou** [comment]
> rock-roboviz

Mmmm. Sorry for that. I'll have a look.

**Comment by doudou** [comment]
Fixed. The fix depends on changes in https://github.com/rock-gui/gui-control_ui/pull/8 as well

**Comment by maltewi** [comment]
I've tested the PR. While welcoming it in principle I see two things. The first thing seems to be a bug, the second I don't know, but maybe you?

1) The mechanism of automatically loading .osgb files seems not to work.
I've tested it with the spaceclimber_multi_visuals data set. Therefor I've placed `.osgb` version of the mesh files intot the same folder as the original `.obj` files. Calling `rock-roboviz SpaceClimber.urdf` within the est_data/spaceclimber_multi_visuals` folder still results in the .obj files being loaded.
Can be seen by loading take long time as compared to loading a .urdf with Search and replace '.obj' --> '.osgb'.

   a) I'm not a real friend of this feature. It creates some unclarity in behaviour. I see people getting confused over the fact, that a different file is loaded than the one which is defined in the URDF/SDF model file. An alternative is proposed in the discussion of #14. Please have a look.

2) I have significantly worse rendering performance on my PC. The test, again the spaceclimber_multi_visuals data set. 
My test:
I performed the optimization offline using the program `optimize_meshes` which I pushed to the PR #14: 
```
SMOOTH=true optimize_meshes *.obj
```
Now loaded a version of the URDF file, that loads the pre-processed `.osgb` files. This is the result:

|                | original file (.obj)  |  .osgb-version after `optimize_meshes` |
| ------------ | ---------- | ------------- |
| this pr      | ~8.5 fps | ~11 fps |
| old master | ~25 fps | ~29 fps |

Graphics board: Intel® HD Graphics 520 (Skylake GT2)
Do you have an idea what's the reason?

**Comment by doudou** [comment]
> The mechanism of automatically loading .osgb files seems not to work.

My guess is that we've not implemented it for URDF.

> a) I'm not a real friend of this feature. It creates some unclarity in behaviour

I agree that it's not perfect. The problem is that having a "base" model and then having to post-process (what you propose) also adds significant complexity in understanding. I personally found the convention of looking for an osgb file along the main mesh file a better trade-off.

On the SDF side, Gazebo does not support osgb, so we get the problem that we can't have the osgb file in the SDF file directly.

**Comment by doudou** [comment]
Just did some tests. Reading the `optimize_meshes` script, it seems that I was not clear enough in my explanations. The convention is to add the extension, i.e. visual_leg0_motor1_an.obj becomes visual_leg0_motor1_an.obj.osgb.

With the osgb files generated with the expected name, I get the following performance for the spaceclimber_multi_visuals on my i7-4700MQ / Intel HD 4600

|               | .obj   | .osgb |
|------------|---------|---------|
| This PR | 2 fps | 29 fps |
| master   | 20 fps | N/A |

The drop in performance with the .obj is expected if the .obj itself is not optimized. I originally did not elect to still run the optimizer on the non-osgb file as it was causing us huge loading times. But then, we now get slow renders. Don't know what would be the best convention here. I don't mind so much either way, as I'm definitely going to create a "asset pipeline" documentation of sorts that allows for the creation of the osgb files.

In addition, loading the file is also significantly faster (from script startup to first visual, there's ~5s of initializing the qt plugins) 

|               | .obj   | .osgb |
|------------|---------|---------|
| This PR | 40s | 7s |
| master   | 24s | N/A |

(FYI, we've originally done this work because loading a ground mesh was taking minutes).

**Comment by doudou** [comment]
Actually, the fps is not representative. Vizkit3d renders at 30fps no matter what, and it does not account for separate CPU and GPU usage. Below are rendering times:

| Test | CPU time | GPU time |
|-------|--------------|--------------|
| .obj, master | 32ms | 32ms |
| .obj, PR | 450ms | 450ms |
| .osgb, PR | 4ms | 12ms |

Note that the .obj version could definitely be as fast as the .osgb version. The main difference is the usage of vertex buffers, and what optimizers are run. What the `.osgb` really adds is better load times (regardless of how much optimization needs to be done on the mesh).

**Comment by maltewi** [comment]
Yes, loading time is faster with osgb. I personally use the format for this reason as well. Removing the optimization step at load time improves loading even more. I think, for that reason it's a valid idea to remove the online optimization, if a tool for performing the optimization is provided at the same time (which is done with `optimize_meshes`).

My problem with this PR is that I can't get same rendering performance as with old master (2. in my previous answer). Maybe this is related to the offline optimization (then same performance should be possible by adjusting parameters in the `optimize_meshes` script). But maybe it's related to something else in the PR. That we've to find out what's causing the slow down.

Here's how I experience the slow down: I apply optimization offline with the `optimize_meshes` script and load a URDF file that loads the osgb versions of the meshes. After loading I press 's' until I see the debug info graph. It shows:
   * ~11fps
   * ~68ms Draw
   * ~63ms GPU 
I also see and feel the slow performance when adjusting the camera.

Comparing with old master and the .obj files (optimization applied, when loading the files) gives:
   * ~25 fps
   * ~17ms Draw
   * ~15ms GPU

As you can see from the numbers, that's a significant loss in performance, which I think is not okay.

**Comment by doudou** [comment]
> As you can see from the numbers, that's a significant loss in performance, which I think is not okay.

I completely understand and agree. As you can see from my numbers, I don't have the same numbers at all. So, next question, what's the difference ?

Just to be sure that we're talking about the same thing:
 - the non-osgb case performance *is* dropping, which is something I would expect. It might be something we want to avoid as well, given that after this PR everyone will get the performance drop.
 - the osgb performance is not present in the tests I did. The `optimize_meshes` script is buggy, and does not generate the expected file names (which causes the .osgb to not be loaded). See https://github.com/rock-gui/gui-robot_model/pull/15 for a fix.

**Comment by doudou** [comment]
Ping ?

**Comment by maltewi** [comment]
Let's isolate the issues we have here:

1. Performance drop on my PC
    * It's commit ed91f954b20ff29e77a0d7db215334a4a6f981cd that causes the slow down. 
2. Don't optimize meshes when loading them
    * That's perfectly okay for me, when there is a tool that does the optimization offline (which we almost have with #14).
3. Automatically choose .osgb version even though the .urdf points to a different file
   * It's not really what I consider nice behavior of a software, because it does something else than the user is telling the program in its configuration file (URDF/SDF). I personally would opt for a tools that prepares the data (URDF/SDF) in the way, that I need it. 
  * But if it's really a very important feature for you, it's okay to add the functionality.

>> The mechanism of automatically loading .osgb files seems not to work.

> My guess is that we've not implemented it for URDF.

I'm happy to see, that is not true. It's working for both. The expected file name pattern is `my_mesh_file.stl.osgb' not `my_mesh_file.osgb' as I have tried it in the first place... so it's working for UDF as well as SDF.. consistent behaviour is a prerequisite and is fulfilled.

So, how do we proceed? My suggestion is to remove ed91f954b20ff29e77a0d7db215334a4a6f981cd and put it on a separated PR such that we can further investigate it without blocking the other points. We'd also not loose the code that you wrote, which seems a reasonable change for the reasons you stated there if there wasn't the performance issue.

The rest can be merged if the auto-select feature is requested..

**Comment by doudou** [comment]
Thanks @maltewi. I generally agree with you on the .osgb feature, but at this stage I don't have the time to spend on making the whole tooling preprocess the SDF/URDF files before it feeds it to whatever is behind it.

I'll put the VBO thing under a runtime flag and set it to false by default, it is a major benefit on my side.

**Comment by maltewi** [comment]
@doudou 
As you suggested: Let's  put the VBO thing under a runtime flag and we can finalize the PR :)

**Comment by doudou** [comment]
I've done it, but I'm going to merge it in an orderly manner in the rock-gazebo fork first. This makes sure that the current users of rock-gazebo are at least warned about the implications.

**Comment by doudou** [comment]
@maltewi: updated

**Pull request merged**
